// NOTE: This file is auto-generated by React Cosmos.
// It imports all fixture and decorator modules, making them available to the
// React Cosmos renderer along with the renderer config.

import type { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as Button from './src/components/ui/Button.fixture';
import * as HeadlessQuestionsEditorDemo from './src/entities/HeadlessEditor/demo/HeadlessQuestionsEditorDemo.fixture';
import * as HeadlessAnswersEditorDemo from './src/entities/HeadlessEditor/demo/HeadlessAnswersEditorDemo.fixture';

import * as decorator0 from './src/entities/HeadlessEditor/demo/cosmos.decorator';

export const rendererConfig: RendererConfig = {
  "webSocketUrl": "ws://192.168.220.1:5000",
  "rendererUrl": "http://localhost:3000/cosmos/<fixture>"
};

const fixtures = {
  'src/components/ui/Button.fixture.tsx': { module: Button },
  'src/entities/HeadlessEditor/demo/HeadlessQuestionsEditorDemo.fixture.tsx': { module: HeadlessQuestionsEditorDemo },
  'src/entities/HeadlessEditor/demo/HeadlessAnswersEditorDemo.fixture.tsx': { module: HeadlessAnswersEditorDemo }
};

const decorators = {
  'src/entities/HeadlessEditor/demo/cosmos.decorator.tsx': { module: decorator0 }
};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
